### ISSUE TITLE
Rendering large SVGs.

### ISSUE THREAD

**Issue by modulovalue** [dnfield/vector_graphics#121]
Hello Dan,

I'm maintaining an SVG renderer for Flutter that is optimized for rendering huge GraphViz graphs (i.e. hundreds of bezier curves and thousands of text/rectangle/ellipse nodes).

It employs various necessary optimizations (that make little sense for small SVGs) such as rendering at different levels of detail or an RTree for efficiently finding groups that need to be rendered for any given viewport.

Would it be correct to assume that it's not a goal of `vector_graphics` to support rendering vector graphics that are that big, or do you plan to eventually support use cases like that?

**Comment by dnfield** [comment]
That's not a current goal of this project - but I'm not opposed to it in principle and would be interested if you have any ideas/documentation to contribute.


/cc @jonahwilliams fyi

**Comment by jonahwilliams** [comment]
This library is designed with trade-offs in mind that make sense for minimal to no iteraction of SVGs and that are sized for assets on mobile applications. I'm not really aware of the extent of the changes we'd need to make to support more interactive viewing or online processing to render large SVGs.

You can always file more specific issues for features you think are missing, but I'd imagine you'd need an entirely different rendering strategy - and this isn't something we're planning on providing.
