### ISSUE TITLE
Add support for drawPicture mode, allow limited configuration

### ISSUE THREAD

**Issue by jonahwilliams** [dnfield/vector_graphics#140]
This render object should support a drawPicture mode that behaves similarly to the previous flutter_svg implementaiton. This should avoid extra compositing by using canvas.saveLayer to apply opacity.

We can allow limited configuration of this mode, with this behavior being the default (outside of google3) and allowing an opt-in to the rasterization support.

**Comment by dnfield** [comment]
Maybe it's not the default, but it'd be the default in flutter_svg?
