### ISSUE TITLE
an build error lass 'Picture'.      - 'Picture' is from 'dart:ui'.     Try correcting the name to the name of an existing method, or defining a method named 'toImageSync'.    rasterPicture.toImageSync(scaledWidth, scaledHeight);

### ISSUE THREAD

**Issue by bill19** [dnfield/vector_graphics#151]
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/9607083/197914255-9fadf5fe-1064-4fd7-bb77-496211d95cff.png">

flutter doctot 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm (Rosetta),
    locale zh-Hans-AR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
Scanning for devices is taking a long time...[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by rahulfromearth** [comment]
`toImageSync` is not available on Flutter 3.3.4 stable
https://github.com/flutter/flutter/issues/77289
We'll have to wait until Flutter 3.5.x is released. I got this same issue.

@dnfield Can we download binaries for Flutter 3.5.0-10.0.pre.78 anywhere?

**Comment by dnfield** [comment]
In general, right now, this package requires a pretty late version of Flutter and may not be compatible with Stable yet. It should work on beta.

**Comment by dnfield** [comment]
I'm a little confused. I think this API should work on 3.3.

**Comment by dnfield** [comment]
Ahh I remember now, it wasn't ready and had to be reverted out of the stable branch. It's availalbe on beta.

**Comment by bill19** [comment]
yes ，i found it。
