### ISSUE TITLE
Shall we have toPicture api?

### ISSUE THREAD

**Issue by zhenpingcui** [dnfield/vector_graphics#170]
Is there any way to expose a ui.Picture from a vector graphic so we can draw it to the canvas dynamically.

**Comment by dnfield** [comment]
You can use `vg.loadPicture`. https://github.com/dnfield/vector_graphics/blob/183bd5c63c9f7e5ba39e318b6709156b5a3b70a3/packages/vector_graphics/lib/src/vector_graphics.dart#L607
