### ISSUE TITLE
Patterns not working for svg

### ISSUE THREAD

**Issue by karanSman** [dnfield/vector_graphics#171]
Hey dnfield i am facing issue while rendering svg with pattern tag. In listerner.dart -> method name onPatternStart has _patterns map which is always empty. Getting below attached error.
![image](https://user-images.githubusercontent.com/107721021/204977821-f48e660a-d388-427a-a744-98311f3b121f.png)

**Here is my svg content:** 
`<svg width='512' height='512' viewBox='0 0 750 750' fill='none' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'><defs><clipPath id='clip_text'><rect x='187' y='570' width='375' height='79' fill='white' /></clipPath><pattern id='pattern0' patternContentUnits='objectBoundingBox' width='1' height='1'><use xlink:href='#image0_27272_8541' transform='translate(0 -0.25) scale(0.003125)' /></pattern><clipPath id='clip0_27272_8541'><rect width='750' height='750' fill='white' /></clipPath><image id='image0_27272_8541' width='320' height='480' xlink:href='{profile_pic}' /></defs><image x='0' y='0' width='750' height='750' xlink:href='https://leadschool-static.s3.ap-south-1.amazonaws.com/parentapp/img/badge/hw_bg.png' /><g clip-path='url(#clip0_27272_8541)'><path opacity='0.08' d='M77.9167 704.167C77.9167 741.254 46.9582 771.667 8.33334 771.667C-30.2915 771.667 -61.25 741.254 -61.25 704.167C-61.25 667.08 -30.2915 636.667 8.33334 636.667C46.9582 636.667 77.9167 667.08 77.9167 704.167Z' stroke='white' stroke-width='15' /><path opacity='0.08' d='M775.833 206.25C775.833 226.105 759.305 242.5 738.542 242.5C717.779 242.5 701.25 226.105 701.25 206.25C701.25 186.395 717.779 170 738.542 170C759.305 170 775.833 186.395 775.833 206.25Z' stroke='white' stroke-width='15' /><circle cx='378' cy='215' r='129' fill='url(#pattern0)' /></g><g clip-path='url(#clip_text)'><text x='375' y='636.839' text-anchor='middle' fill='white' xml:space='preserve' style='white-space: pre' font-family='Poppins' font-size='24' font-weight='500' letter-spacing='0em'>threee</text><text x='375' y='600.839' text-anchor='middle' fill='white' xml:space='preserve' style='white-space: pre' font-family='Poppins' font-size='24' font-weight='bold' letter-spacing='0em'>DON</text></g><image x='0' y='0' width='750' height='750' xlink:href='https://leadschool-static.s3.ap-south-1.amazonaws.com/parentapp/img/badge/hw_strip.png' /></svg>`

**Comment by dnfield** [comment]
That SVG contains network images which we need to support. It also has an invalid reference.

**Comment by karanSman** [comment]
can you help me to know the invalid reference so that i can change.

**Comment by karanSman** [comment]
hi, any update how can i solve patterns for svg?

**Comment by dnfield** [comment]
Ahh I see, the pattern code is broken. Fix incoming... (Sorry, I was offline for a few weeks there)

**Comment by dnfield** [comment]
Your particular example still will not render because it requires network image support though.

**Comment by dnfield** [comment]
I'm going to close this since patterns work now, network images is a separate issue.
