### ISSUE TITLE
Assertion failure: params.length <= 2': is not true

### ISSUE THREAD

**Issue by Maatteogekko** [dnfield/vector_graphics#199]
Using [this](https://upload.wikimedia.org/wikipedia/commons/b/bd/Test.svg) the following assertion throws https://github.com/dnfield/vector_graphics/blob/a74421d7d68b201e9e47ebf22c37ef3ba6699fb7/packages/vector_graphics_compiler/lib/src/svg/parsers.dart#L83

I think the issue is that the svg has a couple of tags like this: `<g transform="translate( 50,1160)">` (with a space inside the translate arguments)

Image attached since Wikipedia changes the test picture from time to time
![Test](https://user-images.githubusercontent.com/54111322/231475883-70b448b7-e27c-4e10-9399-ef31f7e1b2d8.svg)

**Comment by dnfield** [comment]
Yes, the params need a `trim()` as well. This SVG won't work though because it's using a lot of CSS, which isn't supported.

**Comment by dnfield** [comment]
(Afte rrunning this through svgcleaner to get rid of the CSS, none of the text is positioned correctly :\)
