### ISSUE TITLE
Make the magic number public

### ISSUE THREAD

**Issue by shilangyu** [dnfield/vector_graphics#210]
Currently, the magic number is stored as a private constant in [`VectorGraphicsCodec.__magicNumber`](https://github.com/dnfield/vector_graphics/blob/2b8860b4945ab4457b855ebdb7379ca5c3233f00/packages/vector_graphics_codec/lib/vector_graphics_codec.dart#L127). At my company, we are building a program that will need to recognize whether some file is a raw text svg file or a compiled one using `encodeSvg`. A reliable way to do that seems to be to check the header of the binary. Unfortunately the magic number is private. [Tests inside of this repo also use this fact and translate the magic number to a bytes list.](https://github.com/dnfield/vector_graphics/blob/2b8860b4945ab4457b855ebdb7379ca5c3233f00/packages/vector_graphics_codec/test/vector_graphics_codec_test.dart#L11) This issue aims to request for that field to become public, or, understand the reasoning why it should stay private.

If it can be made public I am happy to send a PR for this change.

cc @dnfield

**Comment by dnfield** [comment]
It's private to avoid having anything depend on it.  It may change without notice.

What's the use case?

**Comment by shilangyu** [comment]
As I mentioned:

> to recognize whether some file is a raw text svg file or a compiled one using `encodeSvg`

However if you are saying the magic number is not part of the stable interface on purpose then I will probably have to look for a different solution. Do you think relying on the magic number is a bad usecase?

**Comment by dnfield** [comment]
If it's a SVG file it will be XML (almost certainly UTF-8 encoded). The files produced by this compiler will never be valid XML.

**Comment by dnfield** [comment]
You should be able to just parse the first few bytes - SVG files should always begin with a `<`, perhaps discarding leading whitespace (flutter_svg tolerates I believe it but not everything would).
