### ISSUE TITLE
Differences between 1.1.9 and 1.1.7

### ISSUE THREAD

**Issue by Moshimol** [dnfield/vector_graphics#222]
In version 1.1.9, there is a picture of Scientific notation in SVG that cannot be displayed, but in version 1.1.7, this picture can be displayed。

this is a example for svg string

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="none" version="1.1" width="15.857421875000004" height="31" viewBox="0 0 15.857421875000004 31"><g transform="matrix(-1,-1.2246468525851679e-16,-1.2246468525851679e-16,1,26.714843750000007,1.7763568394002505e-15)"><path d="M11.439151875000004,26.8968L11.438621875000003,26.897400000000005Q11.298881875000003,27.064800000000005,11.190201875000003,27.253700000000002Q11.081531875000003,27.442700000000002,11.007211875000003,27.6477Q10.932881875000003,27.852600000000002,10.895151875000003,28.067300000000003Q10.857421875000004,28.282000000000004,10.857421875000004,28.5Q10.857421875000004,28.612000000000002,10.867441875000004,28.723600000000005Q10.889471875000003,28.968900000000005,10.958911875000004,29.2051Q11.028361875000003,29.4413,11.142551875000004,29.6595Q11.256751875000003,29.8776,11.411311875000003,30.0693Q11.565881875000004,30.261000000000003,11.754861875000003,30.418800000000005Q11.922181875000003,30.558500000000002,12.111161875000004,30.6672Q12.300141875000003,30.7759,12.505074875000004,30.8502Q12.710010875000004,30.924500000000002,12.924717875000004,30.9623Q13.139424875000003,31,13.357421875000004,31L13.370427875000004,31Q13.475944875000003,30.9994,13.581040875000003,30.990000000000002Q13.826281875000003,30.968000000000004,14.062514875000003,30.8985Q14.298746875000003,30.829100000000004,14.516891875000004,30.7149Q14.735041875000004,30.600700000000003,14.926711875000004,30.4461Q15.118391875000004,30.2915,15.276221875000005,30.102600000000002L15.276761875000004,30.1019L25.419821875000004,17.957300000000004Q26.311021875,16.8902,26.311021875,15.500000000000002Q26.311021875,14.109800000000002,25.419821875000004,13.042700000000002L15.276221875000005,0.8974400000000018Q15.100251875000003,0.6867400000000017,14.882741875000004,0.5192500000000018Q14.665241875000003,0.3517500000000018,14.416571875000004,0.23545000000000194Q14.167905875000004,0.11914000000000158,13.899924875000004,0.05957000000000168Q13.631943875000003,1.7763568394002505e-15,13.357422034544003,1.7763568394002505e-15Q13.340054475000004,1.7763568394002505e-15,13.322688775000003,0.0002400000000015723Q13.109086875000003,0.0032100000000019335,12.899083875000004,0.042370000000001795Q12.689081875000003,0.08154000000000172,12.488768875000003,0.15576000000000167Q12.288451875000003,0.2299900000000017,12.103641875000005,0.33712000000000186Q11.918821875000003,0.44426000000000165,11.754861875000003,0.5812000000000017Q11.544161875000004,0.7571700000000017,11.376671875000003,0.9746800000000018Q11.209171875000003,1.1921800000000018,11.092871875000004,1.4408500000000017Q10.976561875000003,1.6895160000000018,10.916991875000004,1.9574970000000018Q10.857421875000004,2.2254780000000016,10.857421875000004,2.5000000000000018Q10.857421875000004,2.517367300000002,10.857661875000003,2.5347331000000017Q10.860631875000003,2.7483350000000017,10.899791875000004,2.9583380000000017Q10.938961875000004,3.168340000000002,11.013181875000004,3.368653000000002Q11.087411875000004,3.568970000000002,11.194541875000004,3.7537800000000017Q11.301681875000003,3.938600000000002,11.438621875000003,4.102560000000002L20.957601875,15.500000000000002L11.439151875000004,26.8968Z" fill-rule="evenodd" fill="#1A1A1A" fill-opacity="1"/></g></svg>

**Comment by Moshimol** [comment]
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="none" version="1.1" width="15.857421875000004" height="30" viewBox="0 0 15.857421875000004 31"><g transform="matrix(-1,-1.2246468525851679e-16,-1.2246468525851679e-16,1,26.714843750000007,1.7763568394002505e-15)"><path d="M11.439151875000004,26.8968L11.438621875000003,26.897400000000005Q11.298881875000003,27.064800000000005,11.190201875000003,27.253700000000002Q11.081531875000003,27.442700000000002,11.007211875000003,27.6477Q10.932881875000003,27.852600000000002,10.895151875000003,28.067300000000003Q10.857421875000004,28.282000000000004,10.857421875000004,28.5Q10.857421875000004,28.612000000000002,10.867441875000004,28.723600000000005Q10.889471875000003,28.968900000000005,10.958911875000004,29.2051Q11.028361875000003,29.4413,11.142551875000004,29.6595Q11.256751875000003,29.8776,11.411311875000003,30.0693Q11.565881875000004,30.261000000000003,11.754861875000003,30.418800000000005Q11.922181875000003,30.558500000000002,12.111161875000004,30.6672Q12.300141875000003,30.7759,12.505074875000004,30.8502Q12.710010875000004,30.924500000000002,12.924717875000004,30.9623Q13.139424875000003,31,13.357421875000004,31L13.370427875000004,31Q13.475944875000003,30.9994,13.581040875000003,30.990000000000002Q13.826281875000003,30.968000000000004,14.062514875000003,30.8985Q14.298746875000003,30.829100000000004,14.516891875000004,30.7149Q14.735041875000004,30.600700000000003,14.926711875000004,30.4461Q15.118391875000004,30.2915,15.276221875000005,30.102600000000002L15.276761875000004,30.1019L25.419821875000004,17.957300000000004Q26.311021875,16.8902,26.311021875,15.500000000000002Q26.311021875,14.109800000000002,25.419821875000004,13.042700000000002L15.276221875000005,0.8974400000000018Q15.100251875000003,0.6867400000000017,14.882741875000004,0.5192500000000018Q14.665241875000003,0.3517500000000018,14.416571875000004,0.23545000000000194Q14.167905875000004,0.11914000000000158,13.899924875000004,0.05957000000000168Q13.631943875000003,1.7763568394002505e-15,13.357422034544003,1.7763568394002505e-15Q13.340054475000004,1.7763568394002505e-15,13.322688775000003,0.0002400000000015723Q13.109086875000003,0.0032100000000019335,12.899083875000004,0.042370000000001795Q12.689081875000003,0.08154000000000172,12.488768875000003,0.15576000000000167Q12.288451875000003,0.2299900000000017,12.103641875000005,0.33712000000000186Q11.918821875000003,0.44426000000000165,11.754861875000003,0.5812000000000017Q11.544161875000004,0.7571700000000017,11.376671875000003,0.9746800000000018Q11.209171875000003,1.1921800000000018,11.092871875000004,1.4408500000000017Q10.976561875000003,1.6895160000000018,10.916991875000004,1.9574970000000018Q10.857421875000004,2.2254780000000016,10.857421875000004,2.5000000000000018Q10.857421875000004,2.517367300000002,10.857661875000003,2.5347331000000017Q10.860631875000003,2.7483350000000017,10.899791875000004,2.9583380000000017Q10.938961875000004,3.168340000000002,11.013181875000004,3.368653000000002Q11.087411875000004,3.568970000000002,11.194541875000004,3.7537800000000017Q11.301681875000003,3.938600000000002,11.438621875000003,4.102560000000002L20.957601875,15.500000000000002L11.439151875000004,26.8968Z" fill-rule="evenodd" fill="#1A1A1A" fill-opacity="1"/></g></svg>

**Comment by Moshimol** [comment]
This SVG cannot be displayed

**Comment by dnfield** [comment]
This is a regression introduced by #208

**Comment by dnfield** [comment]
Sorry, #220 @skreborn fyi

**Comment by dnfield** [comment]
Argh, sorry, my local checkout was dirty.

This was in fact fixed by #220. I am able to render this sVG with 1.1.9.
