### ISSUE TITLE
Migrate away from `elementAt` for Dart 3.3

### ISSUE THREAD

**Issue by dcharkes** [dnfield/vector_graphics#228]
`elementAt` has been deprecated as of Dart 3.3 and should be replaced by `operator +`.

Valid SDK bound for using `operator +`: `"version:3.3.0-279.1.beta"`.

Context:

* https://github.com/dart-lang/sdk/issues/54250

**Comment by dnfield** [comment]
This was done in https://github.com/dnfield/vector_graphics/commit/83517058d2d99e38478861f4329956e9bd9f8199#diff-ab1e22ae020563734f9f8d6ebd6520504de6b0c038d1ffec2134adc613f840b0R122 and was published to pub.dev.

**Comment by dnfield** [comment]
Argh. I think I failed to push this up to github correctly too.

**Comment by dnfield** [comment]
I'm going to re-open this. I didn't publish with theright SDK constraint, and I don't want to publish this until people have had more time to update to a newer version of Flutter.

**Comment by dnfield** [comment]
Oh, but it looks like the indexing operator is available earlier and does the same thing..
