### ISSUE TITLE
Export PDF/SVG/AI/EPS with Layers

### ISSUE THREAD

**Issue by jtkeyva** [dnfield/vector_graphics#233]
I'm a bit confused what this package is capable of. Can it take custompaint and export the lines to be used in vector art programs such as illustrator? Specifically, can it export to standard formats such as EPS/SVG/PDF and does it support layers?
Thanks

**Comment by dnfield** [comment]
No.

This package is for parsing SVG offline into a binary format that can very efficiently be replayed at runtime, and then efficiently rendering it at runtime in a Flutter application.

It does not support export, although it could in theory be used to render to whatever Flutter is capable of rendering to, or some other flutter-canvas-like API.

**Comment by jtkeyva** [comment]
Got it thank you. Having said that, seems it would be a very welcomed addition if the nuts and bolts are already there. Or do you have any other suggestions or possible solutions?
