### ISSUE TITLE
Pub publisher

### ISSUE THREAD

**Issue by spydon** [dnfield/vector_graphics#236]
Maybe these package could be transferred to your publisher (the same one as you have for flutter_svg)?
The dnfield stamp is a pretty good quality stamp. :wink:

**Comment by dnfield** [comment]
This is reasonable. I'm going to figure out whether this is staying here or going to move to flutter/packages. If it's moving it'll be transfered to flutter.dev. If it's not I'll add dnfield.dev.

I need to sync with a couple people to figure that out.
