### ISSUE TITLE
<image> support

### ISSUE THREAD

**Issue by dnfield** [dnfield/vector_graphics#84]
We should support images.

It'd be a lot easier to do after the toImageSync stuff can land - see https://github.com/flutter/flutter/issues/77289 and linked issues

**Comment by jonahwilliams** [comment]
some questions: what format do we support for inline images? We could just do the bytes, no need for base64 since we're not text.

How do we decode these images? Do we make sure they end up in the flutter image cache? if so, do we need to give them some sort of stable identifier?

When rendering a vg, do we delay rendering until image decoding has finished?

**Comment by dnfield** [comment]
1. I think inline images should just be the raw bytes of the original (encoded) image, which will typically be zlib compressed png. It should not be base 64 encoded.
2. This is the harder part. flutter_svg did not put the min the Flutter Image cache and this caused some confusion for customers who were memory sensitive. Instead it ended up in the picture cache with the SVG itself, which VG doesn't have. I think using the image cache would make sense, and we could come up with an ID based on the asset name or network URL of the buffer itself, plus the index of the image in the buffer.
3. I think we delay until image is available. We're not doing progressive rendering anywhere else for this, and right now we just atomically draw the product as a Picture which can't be modified after the fact.

**Comment by jonahwilliams** [comment]
We could also make a cache specifically for vector_graphics, but instead of a global cache more of a Weakreference-based best effort cache. i.e. if you have N vgs with the same image on the page we decode once, but if you leave the screen it still gets cleared. WDUT?

**Comment by dnfield** [comment]
I guess that saves an ImageCache slot for some image the user realizes they're rendering?

I'm a little worried that if we start implementing caching here we'll just get it wrong for some use case and instead should just have a generic way of plugging in a cache for images/pictures - and for images, it should probably just use the Flutter ImageCache interface for people who want to reuse that.

**Comment by jonahwilliams** [comment]
I just don't know how we'd key the image cache entires - I'd be worried about collision at the least

**Comment by dnfield** [comment]
`final String key = '$vectorGraphicKey_$indexOfImage`` right?

That has the potential to add duplicate entries if the same image is used across different vector graphics but oh well

**Comment by jonahwilliams** [comment]
ship it

**Comment by jonahwilliams** [comment]
Now that we're doing eager rasterization, i don't think we need to populate the image cache for inline images (network/asset is another story).
