### ISSUE TITLE
"simple" vg support

### ISSUE THREAD

**Issue by jonahwilliams** [dnfield/vector_graphics#85]
Based on some ideas from @dnfield  and my own thoughts:

For very, very simple vgs : i.e. single path or stroke, we should avoid calling toImage and instead directly apply any opacity or colorblending to the encoded paint.

I had previously encountered some difficulty with this sort of conditional decoding, since we normally don't make the paths/paints accessible in an easy way. Instead perhaps we should use a different runtime structure for this sort of "simple" graphic that allows the vector graphic widget to easily blend its own opacity/colors with the paint.

**Comment by jonahwilliams** [comment]
And of course, this would have to be for a single path, otherwise we'd need to deal with collisions

**Comment by dnfield** [comment]
We could have the compiler emit a field to the header with some kind of complexity score or enum

**Comment by dnfield** [comment]
Or just a field devoted specifically to whether this graphic is worth pre rasterizing

**Comment by jonahwilliams** [comment]
Yeah, something like that and we decode into a slightly different runtime structure.

**Comment by jonahwilliams** [comment]
From some investigation, I've found that performane only improves measurable for very, very low count of path ops, less than 10 or so

**Comment by jonahwilliams** [comment]
From the investigation above, I think we can conclude this isn't really worth it right now, but we can come back to the above if we get a convincing use-case
